enum AffectedAgent
{
  AFFECTED_AGENT = 2048
};
enum PSGModifiers
{
  MDF_AFFECTED = 440,
  MDF_BioHazardHeal = 441
};
enum PSGSymptomIDs 
{
  SYMPTOM_CRUDESERUM = 450,
  SYMPTOM_AFFECTEDFIRST = 452,
  SYMPTOM_AFFECTEDSECOND = 453
};